### ISSUE TITLE
HttpClientAgentJob throws exception when stream dies

### ISSUE THREAD

**Issue by jorelius** [jorelius/Fenrir#12]
Example Exception

Unhandled Exception: System.AggregateException: One or more errors occurred. (Error while copying content to a stream.) ---> System.Net.Http.HttpRequestException: Error while copying content to a stream. ---> System.IO.IOException: The server returned an invalid or unrecognized response.
   at System.Net.Http.HttpConnection.FillAsync()
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.CopyToAsyncCore(Stream destination, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnection.HttpConnectionResponseContent.SerializeToStreamAsync(Stream stream, TransportContext context, CancellationToken cancellationToken)
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpContent.LoadIntoBufferAsyncCore(Task serializeToStreamTask, MemoryStream tempBuffer)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)          at Fenrir.Core.Jobs.HttpClientAgentJob.DoWork() in Z:\git\Fenrir\src\Fenrir.Core\Jobs\HttpClientAgentJob.cs:line 42
   at Fenrir.Core.RequestTreeAgent.<>c.<<Run>b__4_0>d.MoveNext() in Z:\git\Fenrir\src\Fenrir.Core\RequestTreeAgent.cs:line 52
--- End of stack trace from previous location where exception was thrown ---
   at Fenrir.Core.RequestTreeAgent.Run(Int32 threads, CancellationToken cancellationToken) in Z:\git\Fenrir\src\Fenrir.Core\RequestTreeAgent.cs:line 72         at Fenrir.Cli.CliArgs.RunRequestComparisonAsync(Int32 threads, HttpRequestTree requestTree) in Z:\git\Fenrir\src\Fenrir.Cli\CliArgs.cs:line 192
   at Fenrir.Cli.CliArgs.RunRequestTreeAgent(HttpRequestTree requestTree, Int32 Concurrency, String requestSource, String outputFilePath) in Z:\git\Fenrir\src\Fenrir.Cli\CliArgs.cs:line 129
   at Fenrir.Cli.CliArgs.Generator(GeneratorArgs args) in Z:\git\Fenrir\src\Fenrir.Cli\CliArgs.cs:line 82
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at PowerArgs.ArgAction.Invoke()
   at PowerArgs.Args.<>c__DisplayClass17_1.<InvokeAction>b__3()
   at PowerArgs.Args.Execute[T](Func`1 argsProcessingCode)
   at PowerArgs.Args.<>c__DisplayClass17_0.<InvokeAction>b__2(String[] a)
   at PowerArgs.REPL.DriveREPL[T](TabCompletion t, Func`2 eval, String[] args, Func`1 defaultEval)
   at PowerArgs.Args.InvokeAction(CommandLineArgumentsDefinition definition, String[] args)
   at PowerArgs.Args.InvokeAction[T](String[] args)
   at Fenrir.Cli.Program.Main(String[] args) in Z:\git\Fenrir\src\Fenrir.Cli\Program.cs:line 28

**Comment by jorelius** [comment]
protection to this issue is added in the .3.5 tool
